# Agora vamos publicar o conversão de distância (https://github.com/KubeDev/conversao-distancia). 
# E me manda o link do repositório. 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-distancia
spec:
  selector:
    matchLabels:
      app: conversao-distancia
  template:
    metadata:
      labels:
        app: conversao-distancia
    spec:
      containers:
      - name: conversao-distancia
        image: viniciuscaol/conversao-distancia:v1
        resources: {}
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: conversao-distancia-service
spec:
  selector:
    app: conversao-distancia
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer