# Questão 02
# Boa! Agora, é muito importante que você pratique
# também com outros banco de dados.
# Crie um docker compose com o banco de dados MariaDB
# e a ferramenta de interface phpMyAdmin (https://www.phpmyadmin.net).

version: '3.8'

networks: 
  questao02:
    driver: bridge

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
    networks:
      - questao02

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    networks:
      - questao02