# Feita a portabilidade do convers찾o de temperatura para o Kubernetes, 
# chegou a hora de publicar o convers찾o de peso (https://github.com/KubeDev/conversao-peso). 
# N찾o esquece de mandar o link do reposit처rio.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-peso
spec:
  selector:
    matchLabels:
      app: conversao-peso
  template:
    metadata:
      labels:
        app: conversao-peso
    spec:
      containers:
      - name: conversao-peso
        image: viniciuscaol/conversao-peso:v1
        resources: {}
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: conversao-peso-service
spec:
  selector:
    app: conversao-peso
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer